import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HeaderPage } from "../components/header";
import { FooterPage } from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-900">
        <nav>
          <HeaderPage />
        </nav>
        {children}
        <footer>
          <FooterPage />
        </footer>
        </div>
      </body>
    </html>
  );
}
